# Generated by Django 5.0.6 on 2024-05-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jhjlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jhjlist",
            options={
                "ordering": ["-beifen_time", "-create_time"],
                "verbose_name_plural": "交换机列表",
            },
        ),
        migrations.AddField(
            model_name="jhjlist",
            name="beifen",
            field=models.CharField(
                choices=[("0", "未备份"), ("1", "已备份")],
                default=0,
                max_length=6,
                verbose_name="备份状态",
            ),
        ),
        migrations.AddField(
            model_name="jhjlist",
            name="beifen_time",
            field=models.DateTimeField(auto_now=True, verbose_name="备份时间"),
        ),
        migrations.AlterField(
            model_name="jhjlist",
            name="pinpai",
            field=models.CharField(
                choices=[("2", "华为"), ("1", "华三"), ("0", "锐捷")],
                db_index=True,
                default=0,
                help_text="必须选择其中一个品牌",
                max_length=8,
                verbose_name="交换机品牌",
            ),
        ),
    ]
