# Generated by Django 5.0.6 on 2024-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jhjlist", "0003_alter_jhjlist_options_jhjlist_duankou_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jhjlist",
            options={"verbose_name": "交换机列表"},
        ),
        migrations.AddField(
            model_name="jhjlist",
            name="weizhi",
            field=models.CharField(default="机房", max_length=50, verbose_name="设备位置"),
        ),
        migrations.AlterField(
            model_name="jhjlist",
            name="duankou",
            field=models.IntegerField(default=0, verbose_name="管理端口"),
        ),
        migrations.AlterField(
            model_name="jhjlist",
            name="pinpai",
            field=models.CharField(
                choices=[("1", "华三"), ("2", "华为"), ("0", "锐捷")],
                db_index=True,
                default=0,
                help_text="必须选择其中一个品牌",
                max_length=8,
                verbose_name="交换机品牌",
            ),
        ),
    ]
